<a href="https://colab.research.google.com/github/Om-merkle/AI_CAP_MED_EMBED/blob/main/notebooks/run_on_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/Om-merkle/AI_CAP_MED_EMBED/blob/main/notebooks/run_on_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🩺 Medical Embedding Fine-Tuning — run on Colab (free T4 GPU)

End-to-end on the **complete, real medical datasets** pulled straight from the Hugging Face Hub:
prepare data → collect (query, positive, negative) triplets → MTEB medical baseline →
fine-tune (**3 epochs**) → evaluate → before/after comparison.

**Setup (one time):** Runtime → **Change runtime type** → Hardware accelerator = **T4 GPU**.

In [1]:
# Cell 0 — confirm the GPU is on (should print a Tesla T4)
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-d69e3eff-9987-978a-7c5e-5b736b8b3cb5)

In [2]:
# Cell 1 — clone the project + install dependencies (~2 min)
REPO_URL = "https://github.com/Om-merkle/AI_CAP_MED_EMBED"  # <-- set your repo URL

!git clone {REPO_URL} project
%cd project
!pip install -q -r requirements.txt

Cloning into 'project'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 98 (delta 45), reused 84 (delta 31), pack-reused 0 (from 0)
Receiving objects: 100% (98/98), 4.81 MiB | 17.45 MiB/s, done.
Resolving deltas: 100% (45/45), done.
/content/project
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 73.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 121.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 118.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.8/304.8 kB 30.2 MB/s eta 0:00:00

In [3]:
# Cell 2 — optional Hugging Face connection (higher rate limits + enables Hub push).
# Add a secret named HF_TOKEN in Colab's key icon (left sidebar) to use it.
# The datasets are public, so this cell is a safe no-op without a token.
import os
try:
    from google.colab import userdata
    os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")
    print("HF_TOKEN loaded from Colab secrets ✅")
except Exception:
    print("No HF_TOKEN secret found — continuing anonymously (fine for public datasets).")

No HF_TOKEN secret found — continuing anonymously (fine for public datasets).

In [4]:
# Cell 3 — pull the COMPLETE datasets from the Hugging Face Hub (~3-5 min):
#   * all 33,955 medical flashcards (medalpaca)
#   * all ~232,000 MedEmbed clinical triplets (abhinand/MedEmbed-training-triplets-v1)
# This overwrites the small starter sample bundled in data/raw/.
!python scripts/download_dataset.py
!wc -l data/raw/*.jsonl

Downloading medalpaca/medical_meadow_medical_flashcards ...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
README.md: 100% 1.24k/1.24k [00:00<00:00, 4.67MB/s]
medical_meadow_wikidoc_medical_flashcard(…): 100% 17.7M/17.7M [00:01<00:00, 16.0MB/s]
Generating train split: 100% 33955/33955 [00:00<00:00, 101767.12 examples/s]
  wrote 33955 rows -> /content/project/data/raw/medical_flashcards.jsonl
Downloading abhinand/MedEmbed-training-triplets-v1 (COMPLETE, ~232k rows) ...
README.md: 100% 6.36k/6.36k [00:00<00:00, 17.0MB/s]
data/train-00000-of-00001.parquet: 100% 59.7M/59.7M [00:03<00:00, 15.1MB/s]
Generating train split: 100% 232684/232684 [00:00<00:00, 467839.76 examples/s]
  wrote 232684 rows -> /content/project/data/raw/medembed_triplets.jsonl

Done. The `flashcards` and `medembed` domains now run fully offline.
(`nfcorpus` streams BeIR/nfcorpus from the HF Hub on first use.)
   232684 data/raw/medembed_triplets.jsonl
    33955 data/raw/medical_flashcards.jsonl
   266639 total

## Fine-tune (3 epochs) + evaluate on 4 medical benchmarks

Pick a medical domain:
- `nfcorpus` — BeIR medical/nutrition IR (honest before/after on its own benchmark)
- `medembed` — the complete 232k MedEmbed clinical triplets with expert negatives (mining skipped)
- `flashcards` — 34k medical Q/A flashcards

The pipeline evaluates the **base and fine-tuned models on 4 medical MTEB benchmarks**
(MedicalQARetrieval, PublicHealthQA, NFCorpus, ArguAna) and shows per-benchmark
before/after/delta in the comparison and the leaderboard. Add TRECCOVID (the 5th,
~171k docs, slow) with `--mteb-tasks all`. `--benchmark` additionally compares candidate
models (MiniLM vs BGE vs the published MedEmbed) on your triplets.

Expect roughly 60–90 min on a T4 (training + 4 benchmarks × 2 models); add `--no-mteb`
for a fast training-only run.

In [5]:
!python run_pipeline.py --domain nfcorpus --base-model BAAI/bge-small-en-v1.5 \
    --epochs 3 --batch-size 32 --benchmark --run-label colab-nfcorpus-3ep

[device] cuda  |  base_model=BAAI/bge-small-en-v1.5  domain=nfcorpus  primary_task=NFCorpus
[benchmarks] MedicalQARetrieval, PublicHealthQA, NFCorpus, ArguAna

[1/6] Preparing medical data ...
README.md: 100% 10.5k/10.5k [00:00<00:00, 22.4MB/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
corpus/corpus-00000-of-00001.parquet: 100% 3.16M/3.16M [00:00<00:00, 3.21MB/s]
Generating corpus split: 100% 3633/3633 [00:00<00:00, 124602.64 examples/s]
queries/queries-00000-of-00001.parquet: 100% 80.9k/80.9k [00:00<00:00, 128kB/s]
Generating queries split: 100% 3237/3237 [00:00<00:00, 898303.70 examples/s]
README.md: 100% 14.0k/14.0k [00:00<00:00, 35.7MB/s]
train.tsv: 100% 2.50M/2.50M [00:00<00:00, 91.4MB/s]
dev.tsv: 100% 258k/258k [00:00<00:00, 183MB/s]
test.tsv: 100% 280k/280k [00:00<00:00, 190MB/s]
Generating train split: 100% 110575/110575 [00:00<00:00, 1267782.23 examples/s]
Generating validation split: 100% 11385/11385 [00:00<00:00, 857494.45 examples/s]
Generating test split: 100% 12334/12334 [00:00<00:00, 943800.66 examples/s]
{
  "domain": "nfcorpus",
  "num_pairs": 110575,
  "num_eval_queries": 100,
  "eval_corpus_size": 3633,
  "pairs_path": "/content/project/data/pairs.jsonl",
  "eval_path": "/content/project/data/eval.json"
}

[2/6] Collecting triplets ...
modules.json: 100% 349/349 [00:00<00:00, 1.75MB/s]
config_sentence_transformers.json: 100% 124/124 [00:00<00:00, 559kB/s]
README.md: 100% 94.8k/94.8k [00:00<00:00, 109MB/s]
sentence_bert_config.json: 100% 52.0/52.0 [00:00<00:00, 72.8kB/s]
config.json: 100% 743/743 [00:00<00:00, 4.98MB/s]
model.safetensors: 100% 133M/133M [00:01<00:00, 86.2MB/s]
Loading weights: 100% 199/199 [00:00<00:00, 6124.96it/s]
tokenizer_config.json: 100% 366/366 [00:00<00:00, 2.41MB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 25.5MB/s]
tokenizer.json: 100% 711k/711k [00:00<00:00, 71.6MB/s]
special_tokens_map.json: 100% 125/125 [00:00<00:00, 883kB/s]
config.json: 100% 190/190 [00:00<00:00, 1.07MB/s]
Found 2576 unique queries out of 110575 total queries.
Found an average of 42.925 positives per query.
Batches: 100% 111/111 [00:32<00:00,  3.46it/s]
Batches: 100% 81/81 [00:00<00:00, 82.26it/s]
Computing similarity scores: 100% 1/1 [00:00<00:00,  5.34it/s]
Negative candidates mined, preparing dataset...
Metric       Positive       Negative     Difference
Count         109,976          8,238
Mean           0.6226         0.6050         0.0583
Median         0.6216         0.6105         0.0459
Std            0.0775         0.0602         0.0538
Min            0.3325         0.4269         0.0001
25%            0.5698         0.5648         0.0133
50%            0.6216         0.6105         0.0459
75%            0.6735         0.6438         0.0888
Max            0.9304         0.7939         0.2800
Skipped 3,331,669 potential negatives (83.93%) due to the absolute_margin of 0.0.
Could not find enough negatives for 321690 samples (97.50%). Consider adjusting the range_max, range_min and absolute_margin parameters if you'd like to find more valid negatives.
{
  "source": "mined (hard negatives via the base model)",
  "num_triplets": 8238,
  "num_negatives_per_pair": 3,
  "triplets_path": "/content/project/data/triplets.jsonl",
  "columns": [
    "anchor",
    "positive",
    "negative"
  ]
}

[extra] Benchmarking candidate models on the domain triplets ...
modules.json: 100% 349/349 [00:00<00:00, 2.35MB/s]
config_sentence_transformers.json: 100% 116/116 [00:00<00:00, 760kB/s]
README.md: 100% 10.5k/10.5k [00:00<00:00, 33.7MB/s]
sentence_bert_config.json: 100% 53.0/53.0 [00:00<00:00, 86.0kB/s]
config.json: 100% 612/612 [00:00<00:00, 4.35MB/s]
model.safetensors: 100% 90.9M/90.9M [00:01<00:00, 70.0MB/s]
Loading weights: 100% 103/103 [00:00<00:00, 5281.59it/s]
tokenizer_config.json: 100% 350/350 [00:00<00:00, 2.07MB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 17.0MB/s]
tokenizer.json: 100% 466k/466k [00:00<00:00, 54.2MB/s]
special_tokens_map.json: 100% 112/112 [00:00<00:00, 684kB/s]
config.json: 100% 190/190 [00:00<00:00, 1.31MB/s]
Loading weights: 100% 199/199 [00:00<00:00, 4970.15it/s]
modules.json: 100% 349/349 [00:00<00:00, 2.34MB/s]
config_sentence_transformers.json: 100% 201/201 [00:00<00:00, 1.29MB/s]
README.md: 100% 297k/297k [00:00<00:00, 43.5MB/s]
sentence_bert_config.json: 100% 53.0/53.0 [00:00<00:00, 342kB/s]
config.json: 100% 711/711 [00:00<00:00, 3.63MB/s]
model.safetensors: 100% 133M/133M [00:01<00:00, 78.1MB/s]
Loading weights: 100% 199/199 [00:00<00:00, 5087.13it/s]
tokenizer_config.json: 100% 1.24k/1.24k [00:00<00:00, 4.56MB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 41.6MB/s]
tokenizer.json: 100% 711k/711k [00:00<00:00, 86.7MB/s]
special_tokens_map.json: 100% 695/695 [00:00<00:00, 4.54MB/s]
config.json: 100% 296/296 [00:00<00:00, 1.39MB/s]
rank  model                                   triplet_accuracy  avg_margin
1     BAAI/bge-small-en-v1.5                  1.0               0.0709
2     abhinand/MedEmbed-small-v0.1            0.954             0.0734
3     sentence-transformers/all-MiniLM-L6-v2  0.934             0.1871

[3/6] MTEB / IR baseline (base model) ...
Loading weights: 100% 199/199 [00:00<00:00, 5885.60it/s]
2026-07-06 05:39:56.715223: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
README.md: 100% 1.24k/1.24k [00:00<00:00, 1.71MB/s]
default.jsonl: 100% 231k/231k [00:00<00:00, 18.2MB/s]
corpus.jsonl: 100% 2.51M/2.51M [00:00<00:00, 28.4MB/s]
queries.jsonl: 100% 224k/224k [00:00<00:00, 125MB/s]
README.md: 100% 2.07k/2.07k [00:00<00:00, 1.96MB/s]
english.csv: 100% 172k/172k [00:00<00:00, 81.8MB/s]
README.md: 100% 1.46k/1.46k [00:00<00:00, 4.39MB/s]
train.jsonl: 100% 7.26M/7.26M [00:00<00:00, 250MB/s]
dev.jsonl: 100% 748k/748k [00:00<00:00, 272MB/s]
test.jsonl: 100% 810k/810k [00:00<00:00, 126MB/s]
corpus.jsonl: 100% 5.97M/5.97M [00:00<00:00, 6.64MB/s]
queries.jsonl: 100% 180k/180k [00:00<00:00, 294kB/s]
README.md: 100% 1.20k/1.20k [00:00<00:00, 4.73MB/s]
test.jsonl: 100% 157k/157k [00:00<00:00, 192MB/s]
corpus.jsonl: 100% 9.69M/9.69M [00:00<00:00, 10.3MB/s]
queries.jsonl: 100% 1.78M/1.78M [00:00<00:00, 2.18MB/s]
{
  "model": "BAAI/bge-small-en-v1.5",
  "ir": {
    "ndcg@10": 0.3329,
    "mrr@10": 0.5386,
    "map@100": 0.1593,
    "recall@10": 0.1507,
    "accuracy@1": 0.41
  },
  "mteb": {
    "task": "NFCorpus",
    "ndcg@10": 0.3371,
    "tasks": {
      "MedicalQARetrieval": {
        "ndcg@10": 0.6556,
        "mrr@5": 0.5928
      },
      "PublicHealthQA": {
        "ndcg@10": 0.7618,
        "mrr@5": 0.706
      },
      "NFCorpus": {
        "ndcg@10": 0.3371,
        "mrr@5": 0.5219
      },
      "ArguAna": {
        "ndcg@10": 0.595,
        "mrr@5": 0.4978
      }
    }
  }
}

[4/6] Fine-tuning ...
Loading weights: 100% 199/199 [00:00<00:00, 5747.20it/s]
The `warmup_ratio` argument is deprecated in Transformers v5+, and will also be removed from Sentence Transformers once support for Transformers v4 is dropped. Since you're using Transformers v5+, please use `warmup_steps` (as a float) to specify the warmup ratio instead.
{'loss': '2.695', 'grad_norm': '8.046', 'learning_rate': '1.289e-05', 'epoch': '0.1984'}
{'loss': '2.09', 'grad_norm': '9.32', 'learning_rate': '1.932e-05', 'epoch': '0.3968'}
{'loss': '1.706', 'grad_norm': '7.49', 'learning_rate': '1.785e-05', 'epoch': '0.5952'}
{'loss': '1.542', 'grad_norm': '8.945', 'learning_rate': '1.638e-05', 'epoch': '0.7937'}
{'loss': '1.414', 'grad_norm': '9.67', 'learning_rate': '1.491e-05', 'epoch': '0.9921'}
{'loss': '1.173', 'grad_norm': '7.893', 'learning_rate': '1.344e-05', 'epoch': '1.19'}
{'loss': '1.145', 'grad_norm': '7.838', 'learning_rate': '1.197e-05', 'epoch': '1.389'}
{'loss': '0.9847', 'grad_norm': '8.408', 'learning_rate': '1.05e-05', 'epoch': '1.587'}
{'loss': '0.9755', 'grad_norm': '11.03', 'learning_rate': '9.029e-06', 'epoch': '1.786'}
{'loss': '0.8767', 'grad_norm': '9.733', 'learning_rate': '7.559e-06', 'epoch': '1.984'}
{'loss': '0.8138', 'grad_norm': '11.43', 'learning_rate': '6.088e-06', 'epoch': '2.183'}
{'loss': '0.8245', 'grad_norm': '10.5', 'learning_rate': '4.618e-06', 'epoch': '2.381'}
{'loss': '0.7471', 'grad_norm': '8.212', 'learning_rate': '3.147e-06', 'epoch': '2.579'}
{'loss': '0.7848', 'grad_norm': '7.668', 'learning_rate': '1.676e-06', 'epoch': '2.778'}
{'loss': '0.7925', 'grad_norm': '9.034', 'learning_rate': '2.059e-07', 'epoch': '2.976'}
{'train_runtime': '321.9', 'train_samples_per_second': '74.91', 'train_steps_per_second': '2.349', 'train_loss': '1.234', 'epoch': '3'}
Writing model shards: 100% 1/1 [00:00<00:00,  5.34it/s]
{
  "base_model": "BAAI/bge-small-en-v1.5",
  "device": "cuda",
  "fp16": true,
  "epochs": 3,
  "batch_size": 32,
  "num_train_triplets": 8038,
  "num_holdout_triplets": 200,
  "output_dir": "/content/project/models/nfcorpus-bge-small-en-v1.5-ft"
}

[5/6] Evaluating fine-tuned model ...
Loading weights: 100% 199/199 [00:00<00:00, 6838.39it/s]
{
  "model": "/content/project/models/nfcorpus-bge-small-en-v1.5-ft",
  "ir": {
    "ndcg@10": 0.376,
    "mrr@10": 0.6201,
    "map@100": 0.185,
    "recall@10": 0.1733,
    "accuracy@1": 0.53
  },
  "triplet_accuracy": 1.0,
  "mteb": {
    "task": "NFCorpus",
    "ndcg@10": 0.3463,
    "tasks": {
      "MedicalQARetrieval": {
        "ndcg@10": 0.627,
        "mrr@5": 0.5575
      },
      "PublicHealthQA": {
        "ndcg@10": 0.7345,
        "mrr@5": 0.673
      },
      "NFCorpus": {
        "ndcg@10": 0.3463,
        "mrr@5": 0.5382
      },
      "ArguAna": {
        "ndcg@10": 0.5511,
        "mrr@5": 0.4534
      }
    }
  }
}

[6/6] Comparison (before vs after) ...
{
  "base_model": "BAAI/bge-small-en-v1.5",
  "finetuned_model": "/content/project/models/nfcorpus-bge-small-en-v1.5-ft",
  "headline_ir_ndcg@10_delta": 0.0431,
  "improved": true,
  "triplet_accuracy_finetuned": 1.0,
  "rows": [
    {
      "metric": "IR ndcg@10",
      "baseline": 0.3329,
      "finetuned": 0.376,
      "delta": 0.0431
    },
    {
      "metric": "IR mrr@10",
      "baseline": 0.5386,
      "finetuned": 0.6201,
      "delta": 0.0815
    },
    {
      "metric": "IR map@100",
      "baseline": 0.1593,
      "finetuned": 0.185,
      "delta": 0.0257
    },
    {
      "metric": "IR recall@10",
      "baseline": 0.1507,
      "finetuned": 0.1733,
      "delta": 0.0226
    },
    {
      "metric": "MTEB MedicalQARetrieval ndcg@10",
      "baseline": 0.6556,
      "finetuned": 0.627,
      "delta": -0.0286
    },
    {
      "metric": "MTEB PublicHealthQA ndcg@10",
      "baseline": 0.7618,
      "finetuned": 0.7345,
      "delta": -0.0273
    },
    {
      "metric": "MTEB NFCorpus ndcg@10",
      "baseline": 0.3371,
      "finetuned": 0.3463,
      "delta": 0.0092
    },
    {
      "metric": "MTEB ArguAna ndcg@10",
      "baseline": 0.595,
      "finetuned": 0.5511,
      "delta": -0.0439
    }
  ]
}

=== DONE: IR nDCG@10 delta = 0.0431  ->  IMPROVED ===

=== LEADERBOARD (best first) ===
rank  run_at               run_label           base_model              domain    epochs  ir_ndcg@10_ft  mteb_MedicalQARetrieval_ft  mteb_PublicHealthQA_ft  mteb_NFCorpus_ft  mteb_ArguAna_ft  llm_cost_usd
1     2026-07-06 05:49:27  colab-nfcorpus-3ep  BAAI/bge-small-en-v1.5  nfcorpus  3       0.376          0.627                       0.7345                  0.3463            0.5511           -

In [6]:
# Before/after comparison — fine-tuned nDCG@10 should beat the baseline.
import json
print(json.dumps(json.load(open("results/comparison.json")), indent=2))

{
  "base_model": "BAAI/bge-small-en-v1.5",
  "finetuned_model": "/content/project/models/nfcorpus-bge-small-en-v1.5-ft",
  "headline_ir_ndcg@10_delta": 0.0431,
  "improved": true,
  "triplet_accuracy_finetuned": 1.0,
  "rows": [
    {
      "metric": "IR ndcg@10",
      "baseline": 0.3329,
      "finetuned": 0.376,
      "delta": 0.0431
    },
    {
      "metric": "IR mrr@10",
      "baseline": 0.5386,
      "finetuned": 0.6201,
      "delta": 0.0815
    },
    {
      "metric": "IR map@100",
      "baseline": 0.1593,
      "finetuned": 0.185,
      "delta": 0.0257
    },
    {
      "metric": "IR recall@10",
      "baseline": 0.1507,
      "finetuned": 0.1733,
      "delta": 0.0226
    },
    {
      "metric": "MTEB MedicalQARetrieval ndcg@10",
      "baseline": 0.6556,
      "finetuned": 0.627,
      "delta": -0.0286
    },
    {
      "metric": "MTEB PublicHealthQA ndcg@10",
      "baseline": 0.7618,
      "finetuned": 0.7345,
      "delta": -0.0273
    },
    {
      "metric": "MTEB NFCorpus ndcg@10",
      "baseline": 0.3371,
      "finetuned": 0.3463,
      "delta": 0.0092
    },
    {
      "metric": "MTEB ArguAna ndcg@10",
      "baseline": 0.595,
      "finetuned": 0.5511,
      "delta": -0.0439
    }
  ]
}

In [7]:
# Ranked leaderboard of every run so far (persists in results/leaderboard.csv).
from core import leaderboard
leaderboard.to_dataframe()

,run_at,run_label,base_model,domain,device,epochs,batch_size,sample_size,num_triplets,ir_ndcg@10_base,...,mteb_ArguAna_ft,mteb_ArguAna_delta,mteb_TRECCOVID_base,mteb_TRECCOVID_ft,mteb_TRECCOVID_delta,triplet_accuracy,llm_model,llm_input_tokens,llm_output_tokens,llm_cost_usd
0,2026-07-06 05:49:27,colab-nfcorpus-3ep,BAAI/bge-small-en-v1.5,nfcorpus,cuda,3,32,,8238,0.3329,...,0.5511,-0.0439,,,,1.0,,,,

## 🏆 Medical benchmark leaderboard (MedEmbed-style)

The full benchmark table from the MedEmbed project: every model evaluated on the same
official medical MTEB tasks, **nDCG@10 + MRR@5 per task**, best score per column in
**bold**, and your fine-tuned model highlighted in green.

Results are cached in `results/med_benchmarks.json` — re-running only evaluates what's new.
`QUICK_TASKS` skips TRECCOVID (~171k docs, by far the slowest); switch to
`med_leaderboard.DEFAULT_TASKS` for the complete 5-task table (~1-2 h extra on a T4).

In [8]:
from core import med_leaderboard

MODELS = [
    "sentence-transformers/all-MiniLM-L6-v2",
    "BAAI/bge-small-en-v1.5",
    "abhinand/MedEmbed-small-v0.1",
    "models/nfcorpus-bge-small-en-v1.5-ft",   # <- your fine-tuned model (from the run above)
]
TASKS = med_leaderboard.QUICK_TASKS  # or med_leaderboard.DEFAULT_TASKS to add TRECCOVID

med_leaderboard.evaluate(models=MODELS, tasks=TASKS)
med_leaderboard.styled(tasks=TASKS)

[evaluating] sentence-transformers/all-MiniLM-L6-v2 on ['MedicalQARetrieval', 'PublicHealthQA', 'NFCorpus', 'ArguAna']

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

[evaluating] BAAI/bge-small-en-v1.5 on ['MedicalQARetrieval', 'PublicHealthQA', 'NFCorpus', 'ArguAna']

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[evaluating] abhinand/MedEmbed-small-v0.1 on ['MedicalQARetrieval', 'PublicHealthQA', 'NFCorpus', 'ArguAna']

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[evaluating] models/nfcorpus-bge-small-en-v1.5-ft on ['MedicalQARetrieval', 'PublicHealthQA', 'NFCorpus', 'ArguAna']

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

## More experiments (each adds a leaderboard row)

In [9]:
# Train on the COMPLETE MedEmbed clinical triplets (expert negatives, mining skipped).
# ~232k triplets x 3 epochs is a long T4 run — cap with --sample-size if short on time.
!python run_pipeline.py --domain medembed --epochs 3 --batch-size 32 --run-label colab-medembed-3ep

# Or the complete medical flashcards:
# !python run_pipeline.py --domain flashcards --epochs 3 --batch-size 32 --run-label colab-flashcards-3ep

[device] cuda  |  base_model=BAAI/bge-small-en-v1.5  domain=medembed  primary_task=MedicalQARetrieval
[benchmarks] MedicalQARetrieval, PublicHealthQA, NFCorpus, ArguAna

[1/6] Preparing medical data ...
{
  "domain": "medembed",
  "num_pairs": 21585,
  "num_eval_queries": 100,
  "eval_corpus_size": 5000,
  "pairs_path": "/content/project/data/pairs.jsonl",
  "eval_path": "/content/project/data/eval.json"
}

[2/6] Collecting triplets ...
{
  "source": "native (dataset ships expert triplets; mining skipped)",
  "num_triplets": 21585,
  "triplets_path": "/content/project/data/triplets.jsonl"
}

[3/6] MTEB / IR baseline (base model) ...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 199/199 [00:00<00:00, 6401.41it/s]
{
  "model": "BAAI/bge-small-en-v1.5",
  "ir": {
    "ndcg@10": 0.38,
    "mrr@10": 0.351,
    "map@100": 0.3575,
    "recall@10": 0.47,
    "accuracy@1": 0.29
  },
  "mteb": {
    "task": "MedicalQARetrieval",
    "ndcg@10": 0.6556,
    "tasks": {
      "MedicalQARetrieval": {
        "ndcg@10": 0.6556,
        "mrr@5": 0.5928
      },
      "PublicHealthQA": {
        "ndcg@10": 0.7618,
        "mrr@5": 0.706
      },
      "NFCorpus": {
        "ndcg@10": 0.3371,
        "mrr@5": 0.5219
      },
      "ArguAna": {
        "ndcg@10": 0.595,
        "mrr@5": 0.4978
      }
    }
  }
}

[4/6] Fine-tuning ...
Loading weights: 100% 199/199 [00:00<00:00, 5719.87it/s]
The `warmup_ratio` argument is deprecated in Transformers v5+, and will also be removed from Sentence Transformers once support for Transformers v4 is dropped. Since you're using Transformers v5+, please use `warmup_steps` (as a float) to specify the warmup ratio instead.
{'loss': '2.729', 'grad_norm': '7.414', 'learning_rate': '4.876e-06', 'epoch': '0.07474'}
{'loss': '2.206', 'grad_norm': '8.051', 'learning_rate': '9.851e-06', 'epoch': '0.1495'}
{'loss': '1.888', 'grad_norm': '9.731', 'learning_rate': '1.483e-05', 'epoch': '0.2242'}
{'loss': '1.789', 'grad_norm': '7.975', 'learning_rate': '1.98e-05', 'epoch': '0.299'}
{'loss': '1.711', 'grad_norm': '9.269', 'learning_rate': '1.947e-05', 'epoch': '0.3737'}
{'loss': '1.636', 'grad_norm': '8.559', 'learning_rate': '1.891e-05', 'epoch': '0.4484'}
{'loss': '1.606', 'grad_norm': '9.766', 'learning_rate': '1.836e-05', 'epoch': '0.5232'}
{'loss': '1.594', 'grad_norm': '10.18', 'learning_rate': '1.781e-05', 'epoch': '0.5979'}
{'loss': '1.572', 'grad_norm': '9.686', 'learning_rate': '1.725e-05', 'epoch': '0.6726'}
{'loss': '1.579', 'grad_norm': '9.953', 'learning_rate': '1.67e-05', 'epoch': '0.7474'}
{'loss': '1.498', 'grad_norm': '10.26', 'learning_rate': '1.615e-05', 'epoch': '0.8221'}
{'loss': '1.523', 'grad_norm': '10.49', 'learning_rate': '1.559e-05', 'epoch': '0.8969'}
{'loss': '1.531', 'grad_norm': '9.442', 'learning_rate': '1.504e-05', 'epoch': '0.9716'}
{'loss': '1.436', 'grad_norm': '10.49', 'learning_rate': '1.449e-05', 'epoch': '1.046'}
{'loss': '1.424', 'grad_norm': '8.779', 'learning_rate': '1.393e-05', 'epoch': '1.121'}
{'loss': '1.341', 'grad_norm': '9.464', 'learning_rate': '1.338e-05', 'epoch': '1.196'}
{'loss': '1.376', 'grad_norm': '10.22', 'learning_rate': '1.282e-05', 'epoch': '1.271'}
{'loss': '1.358', 'grad_norm': '8.844', 'learning_rate': '1.227e-05', 'epoch': '1.345'}
{'loss': '1.354', 'grad_norm': '10.75', 'learning_rate': '1.172e-05', 'epoch': '1.42'}
{'loss': '1.352', 'grad_norm': '9.273', 'learning_rate': '1.116e-05', 'epoch': '1.495'}
{'loss': '1.309', 'grad_norm': '11.56', 'learning_rate': '1.061e-05', 'epoch': '1.57'}
{'loss': '1.289', 'grad_norm': '8.947', 'learning_rate': '1.006e-05', 'epoch': '1.644'}
{'loss': '1.333', 'grad_norm': '11.47', 'learning_rate': '9.502e-06', 'epoch': '1.719'}
{'loss': '1.354', 'grad_norm': '10.9', 'learning_rate': '8.948e-06', 'epoch': '1.794'}
{'loss': '1.276', 'grad_norm': '10.11', 'learning_rate': '8.394e-06', 'epoch': '1.868'}
{'loss': '1.354', 'grad_norm': '10.66', 'learning_rate': '7.841e-06', 'epoch': '1.943'}
{'loss': '1.342', 'grad_norm': '9.421', 'learning_rate': '7.287e-06', 'epoch': '2.018'}
{'loss': '1.3', 'grad_norm': '10.96', 'learning_rate': '6.733e-06', 'epoch': '2.093'}
{'loss': '1.193', 'grad_norm': '9.948', 'learning_rate': '6.179e-06', 'epoch': '2.167'}
{'loss': '1.203', 'grad_norm': '9.152', 'learning_rate': '5.626e-06', 'epoch': '2.242'}
{'loss': '1.239', 'grad_norm': '12.36', 'learning_rate': '5.072e-06', 'epoch': '2.317'}
{'loss': '1.205', 'grad_norm': '9.818', 'learning_rate': '4.518e-06', 'epoch': '2.392'}
{'loss': '1.264', 'grad_norm': '8.065', 'learning_rate': '3.965e-06', 'epoch': '2.466'}
{'loss': '1.155', 'grad_norm': '9.136', 'learning_rate': '3.411e-06', 'epoch': '2.541'}
{'loss': '1.215', 'grad_norm': '10.67', 'learning_rate': '2.857e-06', 'epoch': '2.616'}
{'loss': '1.245', 'grad_norm': '10.49', 'learning_rate': '2.303e-06', 'epoch': '2.691'}
{'loss': '1.193', 'grad_norm': '9.055', 'learning_rate': '1.75e-06', 'epoch': '2.765'}
{'loss': '1.26', 'grad_norm': '9.453', 'learning_rate': '1.196e-06', 'epoch': '2.84'}
{'loss': '1.206', 'grad_norm': '9.844', 'learning_rate': '6.423e-07', 'epoch': '2.915'}
{'loss': '1.272', 'grad_norm': '10.95', 'learning_rate': '8.859e-08', 'epoch': '2.99'}
{'train_runtime': '346.5', 'train_samples_per_second': '185.1', 'train_steps_per_second': '5.792', 'train_loss': '1.442', 'epoch': '3'}
Writing model shards: 100% 1/1 [00:00<00:00,  4.39it/s]
{
  "base_model": "BAAI/bge-small-en-v1.5",
  "device": "cuda",
  "fp16": true,
  "epochs": 3,
  "batch_size": 32,
  "num_train_triplets": 21385,
  "num_holdout_triplets": 200,
  "output_dir": "/content/project/models/medembed-bge-small-en-v1.5-ft"
}

[5/6] Evaluating fine-tuned model ...
Loading weights: 100% 199/199 [00:00<00:00, 6867.25it/s]
{
  "model": "/content/project/models/medembed-bge-small-en-v1.5-ft",
  "ir": {
    "ndcg@10": 0.4212,
    "mrr@10": 0.388,
    "map@100": 0.3932,
    "recall@10": 0.53,
    "accuracy@1": 0.33
  },
  "triplet_accuracy": 0.79,
  "mteb": {
    "task": "MedicalQARetrieval",
    "ndcg@10": 0.6919,
    "tasks": {
      "MedicalQARetrieval": {
        "ndcg@10": 0.6919,
        "mrr@5": 0.6361
      },
      "PublicHealthQA": {
        "ndcg@10": 0.7953,
        "mrr@5": 0.7393
      },
      "NFCorpus": {
        "ndcg@10": 0.3376,
        "mrr@5": 0.5175
      },
      "ArguAna": {
        "ndcg@10": 0.5985,
        "mrr@5": 0.504
      }
    }
  }
}

[6/6] Comparison (before vs after) ...
{
  "base_model": "BAAI/bge-small-en-v1.5",
  "finetuned_model": "/content/project/models/medembed-bge-small-en-v1.5-ft",
  "headline_ir_ndcg@10_delta": 0.0412,
  "improved": true,
  "triplet_accuracy_finetuned": 0.79,
  "rows": [
    {
      "metric": "IR ndcg@10",
      "baseline": 0.38,
      "finetuned": 0.4212,
      "delta": 0.0412
    },
    {
      "metric": "IR mrr@10",
      "baseline": 0.351,
      "finetuned": 0.388,
      "delta": 0.037
    },
    {
      "metric": "IR map@100",
      "baseline": 0.3575,
      "finetuned": 0.3932,
      "delta": 0.0357
    },
    {
      "metric": "IR recall@10",
      "baseline": 0.47,
      "finetuned": 0.53,
      "delta": 0.06
    },
    {
      "metric": "MTEB MedicalQARetrieval ndcg@10",
      "baseline": 0.6556,
      "finetuned": 0.6919,
      "delta": 0.0363
    },
    {
      "metric": "MTEB PublicHealthQA ndcg@10",
      "baseline": 0.7618,
      "finetuned": 0.7953,
      "delta": 0.0335
    },
    {
      "metric": "MTEB NFCorpus ndcg@10",
      "baseline": 0.3371,
      "finetuned": 0.3376,
      "delta": 0.0005
    },
    {
      "metric": "MTEB ArguAna ndcg@10",
      "baseline": 0.595,
      "finetuned": 0.5985,
      "delta": 0.0035
    }
  ]
}

=== DONE: IR nDCG@10 delta = 0.0412  ->  IMPROVED ===

=== LEADERBOARD (best first) ===
rank  run_at               run_label           base_model              domain    epochs  ir_ndcg@10_ft  mteb_MedicalQARetrieval_ft  mteb_PublicHealthQA_ft  mteb_NFCorpus_ft  mteb_ArguAna_ft  llm_cost_usd
1     2026-07-06 06:06:28  colab-medembed-3ep  BAAI/bge-small-en-v1.5  medembed  3       0.4212         0.6919                      0.7953                  0.3376            0.5985           -
2     2026-07-06 05:49:27  colab-nfcorpus-3ep  BAAI/bge-small-en-v1.5  nfcorpus  3       0.376          0.627                       0.7345                  0.3463            0.5511           -

## Download the fine-tuned model + results

In [10]:
!zip -rq finetuned_model.zip models/ results/
from google.colab import files
files.download("finetuned_model.zip")

**Use the model afterwards:**

```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("models/nfcorpus-bge-small-en-v1.5-ft")
emb = model.encode(["What are the symptoms of type 2 diabetes?"], normalize_embeddings=True)
```